### PR TITLE
Add tests for double-ended iterator behavior.

### PR DESCRIPTION
**Pull request by jimblandy**
The crate provides the following implementations of DoubleEndedFallibleIterator:

- Chain: double-ended behavior already tested
- Convert: used throughout existing tests
- Cloned: untested but trivial
- Filter: added new tests
- FilterMap: added new tests
- Iterator: added new tests
- Map: added new tests
- MapErr: added new tests

### CODE REVIEW

**Comment by jimblandy** [comment]
[Edit: I can reproduce this now. I must have screwed up my override to 1.19.0.]

I'm sort of at a loss as to why the stable CI failed. I checked out 1.19.0 and rebuilt with that, but it worked fine. The changeset checked out is 0034e59, which has pull request #10 as a parent.

If someone could take a look at this and make sure I haven't done anything dumb, then I'll pursue it more tomorrow.

**Comment by jimblandy** [comment]
The `stable` CI tests are failing because they use Rust 1.19.0, which will not implement `Clone` for closures. Hence, any iterator adapter that takes a closure (which is most of them; `chain` is one that does not) cannot have the iterators it returns implement `Clone`. The tests happen to take advantage of pull request #10, so they fail if the compiler is not cooperative.

Rust [has been implementing `Clone` for suitable closures since version 1.26.0][v26], which was released 2018-5-10.

@sfackler, would you like the tests to continue to work on older compilers, or could we simply update the stable rustc to something more recent?

[v26]: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1260-2018-05-10

**Comment by jimblandy** [comment]
Confirmed in #14 that updating the nightly to 1.26.0 fixes these failures.

**Comment by sfackler** [comment]
Given that we'll be cutting a new major release with other changes it seems fine to bump the minimum version.

**Comment by sfackler** [comment]
You should be able to rebase this now that we've merged #14

**Comment by jimblandy** [comment]
[EDIT: I completely misunderstood what sfackler meant. Nothing to see here...]

> Given that we'll be cutting a new major release with other changes it seems fine to bump the minimum version.

Oh, I see - even though this doesn't break the API per se, it does introduce a change that would cause tests to fail for people using older compilers, so we could save them trouble by bumping the version now? Okay, I'll amend the commit.

**Comment by jimblandy** [comment]
@sfackler Okay, here's a nice green PR.

**Pull request merged**
