### PR TITLE
Add #![no_std] support

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks!

**Comment by whitequark** [comment]
Heads-up: looks like Travis didn't test the commit. I've verified it locally though so it should be fine (I think).

Also, can you please cut a release so I can use this for gimli?

**Comment by sfackler** [comment]
Yeah I'll fix up the CI and cut a release.

**Comment by sfackler** [comment]
Done!

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
